### ISSUE TITLE
Application crashes when choosing to manually insert data

### ISSUE THREAD

**Issue by alehuo** [jehna/kryptovero.fi#23]
Google Chrome, Version 98.0.4758.102 (Official Build) (x86_64)

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/7612995/157277763-852ea9aa-2ea4-4b69-81c4-6033a0715573.png">

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at Object.GetFormatterParts (_app-dac2e74ea2002737914d.js:1:228416)
    at Object.GetIANATimeZoneDateTimeParts (_app-dac2e74ea2002737914d.js:1:227298)
    at Object.GetIANATimeZoneOffsetNanoseconds (_app-dac2e74ea2002737914d.js:1:225834)
    at e.value (_app-dac2e74ea2002737914d.js:1:258333)
    at Object.he [as Call] (_app-dac2e74ea2002737914d.js:1:123933)
    at Object.GetOffsetNanosecondsFor (_app-dac2e74ea2002737914d.js:1:217892)
    at Object.BuiltinTimeZoneGetPlainDateTimeFor (_app-dac2e74ea2002737914d.js:1:218297)
    at Object.TemporalInstantToString (_app-dac2e74ea2002737914d.js:1:220538)
    at new e (_app-dac2e74ea2002737914d.js:1:268178)
    at Qo (_app-dac2e74ea2002737914d.js:1:313893)`

**Comment by jehna** [comment]
That's interesting. Same happening with Firefox.

**Comment by AnttiBoman** [comment]
Firefox has the same visible error, but developer console shows a different one:

```
TypeError: a is undefined
    NextJS 26
        GetFormatterParts
        GetIANATimeZoneDateTimeParts
        GetIANATimeZoneOffsetNanoseconds
        value
        he
        GetOffsetNanosecondsFor
        BuiltinTimeZoneGetPlainDateTimeFor
        TemporalInstantToString
        e
        Qo
        o
        $o
        Xo
        2687
        r
        4656
        onEntrypoint
        promise callback*onEntrypoint
        Y
        4656
        r
        <anonymous>
        O
        <anonymous>
        e
        <anonymous>
main-0961e706c00be0a62372.js:1:7617
```

Happy to help if needed!
